"""reminder lead time

Revision ID: 252e69e29d3b
Revises: f3fd9dea470f
Create Date: 2026-10-01 06:59:55.592870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252e69e29d3b'
down_revision: Union[str, Sequence[str], None] = 'f3fd9dea470f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('reminder_lead_minutes', sa.Integer(), nullable=False, server_default='15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'reminder_lead_minutes')
    # ### end Alembic commands ###
