"""cascade conversation deletes

Revision ID: 32e2f58d7ee6
Revises: 34f827d904eb
Create Date: 2026-09-30 08:19:06.092451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e2f58d7ee6'
down_revision: Union[str, Sequence[str], None] = '34f827d904eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_participant_conversation_id_fkey'), 'conversation_participant', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participant_conversation_id_fkey'), 'conversation_participant', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('file_embedding_file_id_fkey'), 'file_embedding', type_='foreignkey')
    op.create_foreign_key(op.f('file_embedding_file_id_fkey'), 'file_embedding', 'uploaded_file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('message_conversation_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_conversation_id_fkey'), 'message', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messageembedding_message_id_fkey'), 'messageembedding', type_='foreignkey')
    op.create_foreign_key(op.f('messageembedding_message_id_fkey'), 'messageembedding', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uploaded_file_conversation_id_fkey'), 'uploaded_file', type_='foreignkey')
    op.create_foreign_key(op.f('uploaded_file_conversation_id_fkey'), 'uploaded_file', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uploaded_file_conversation_id_fkey'), 'uploaded_file', type_='foreignkey')
    op.create_foreign_key(op.f('uploaded_file_conversation_id_fkey'), 'uploaded_file', 'conversation', ['conversation_id'], ['id'])
    op.drop_constraint(op.f('messageembedding_message_id_fkey'), 'messageembedding', type_='foreignkey')
    op.create_foreign_key(op.f('messageembedding_message_id_fkey'), 'messageembedding', 'message', ['message_id'], ['id'])
    op.drop_constraint(op.f('message_conversation_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_conversation_id_fkey'), 'message', 'conversation', ['conversation_id'], ['id'])
    op.drop_constraint(op.f('file_embedding_file_id_fkey'), 'file_embedding', type_='foreignkey')
    op.create_foreign_key(op.f('file_embedding_file_id_fkey'), 'file_embedding', 'uploaded_file', ['file_id'], ['id'])
    op.drop_constraint(op.f('conversation_participant_conversation_id_fkey'), 'conversation_participant', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participant_conversation_id_fkey'), 'conversation_participant', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
