"""add reminder table

Revision ID: f3fd9dea470f
Revises: 7a1afef9e0dc
Create Date: 2026-10-01 05:14:51.859194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3fd9dea470f'
down_revision: Union[str, Sequence[str], None] = '7a1afef9e0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_conversation_id'), 'reminder', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_reminder_due_at'), 'reminder', ['due_at'], unique=False)
    op.create_index(op.f('ix_reminder_message_id'), 'reminder', ['message_id'], unique=False)
    op.create_index(op.f('ix_reminder_user_id'), 'reminder', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_user_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_message_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_due_at'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_conversation_id'), table_name='reminder')
    op.drop_table('reminder')
    # ### end Alembic commands ###
